spring.application.name=QuanLiThuChi

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HuyvaHungstore
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Data Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Server Configuration
server.port=8080
spring.thymeleaf.cache=false

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# UTF-8 Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8

# Public base URL for links in notifications
app.web-base-url=http://localhost:8080

# Email SMTP Notification Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hellovietnam1910@gmail.com
spring.mail.password=svcg rvnq bigx rabl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Multipart Upload Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Config
cloudinary.cloud-name=dxjwa3jdl
cloudinary.api-key=863496584398644
cloudinary.api-secret=VnjU5Nyjh2RyUtSz1LzzFjNvDl0

notification.email.admin-email=hellovietnam1910@gmail.com
